version: "3.8"
services:
  paradedb:
    image: paradedb/paradedb:latest
    container_name: paradedb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - paradedb_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@paradedb:5432/${DB_NAME}
    volumes:
      - open-webui:/app/backend/data
volumes:
  paradedb_data:
  open-webui: