version: "3.8"
services:
  paradedb:
    image: paradedb/paradedb:latest
    container_name: paradedb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - paradedb_data:/var/lib/postgresql/data

volumes:
  paradedb_data:
